export default {
    cols: Number,
    rows: Number,
    convertEol: Boolean,
    termName: String,
    cursorBlink: Boolean,
    cursorStyle: String,
    bellSound: String,
    bellStyle: String,
    enableBold: Boolean,
    fontFamily: String,
    fontSize: Number,
    fontWeight: String,
    fontWeightBold: String,
    lineHeight: Number,
    letterSpacing: Number,
    scrollback: Number,
    screenKeys: Boolean,
    debug: Boolean,
    macoptionsIsMeta: Boolean,
    cancelEvents: Boolean,
    disableStdin: Boolean,
    useFlowControl: Boolean,
    allowTransparency: Boolean,
    tabStopWidth: Number,
    theme: Object,
}